source 'http://rubygems.org'

gem 'rails', '3.0.0'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'haml', :git => 'http://github.com/nex3/haml.git'
gem 'haml-rails', '0.2'
gem 'compass', '0.10.5'
gem 'dynamic_form', :git => 'git://github.com/johngrimes/dynamic_form.git'

gem 't-minus', :path => '../../'
gem 'campaigning'

group :development do
  gem 'autotest', '4.3.2'
  gem 'ruby-debug', '0.10.3'
end

group :development, :test do
  gem 'rspec', '2.0.0.beta.22'
  gem 'rspec-rails', '2.0.0.beta.22'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'webrat'
  gem 'nokogiri'
end

group :test do
  gem 'mocha', '0.9.8'
end
