source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'haml-rails'

gem 't-minus', :path => '../../'

gem 'rspec-rails', '2.0.0.beta.22'
gem 'mocha'
gem 'cucumber-rails'
gem 'webrat'
gem 'nokogiri'
