source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

gem 't-minus', :path => '../../'
gem 'campaigning'

gem 'rspec', '2.0.0.beta.22'
gem 'rspec-rails', '2.0.0.beta.22'
gem 'cucumber'
gem 'cucumber-rails'
gem 'webrat'
gem 'nokogiri'
